### PR TITLE
Updates for 2.0.0 pre-release branch

### PR DESCRIPTION
**Pull request by jordangray**
Significant updates for the 2.0.0 pre-release branch.
- Decoupled serialisation and column resolution for improved extensibility. [Issue #43]
- Additional serialisation options for expando objects and per-request column selection. [Issue #45]
- Expanded documentation.
- Updated dependencies.
- Major refactoring.

### CODE REVIEW

**Comment by jordangray** [comment]
Hey @ChrisMissal, quick question! When I merge this to the **pre** branch, would you be able to make a pre-release NuGet build of this as version `1.1.0-pre`? I'd like to get feedback on some of these changes before I push them live! :)

**Comment by jordangray** [comment]
Hmm… there are a few breaking changes with this version.
1. Moved core functionality to more specific namespaces, e.g. `WebApiContrib.Formatting.Xlsx.ExcelColumnAttribute` to `WebApiContrib.Formatting.Xlsx.Attributes.ExcelColumnAttribute`.
2. Renamed a few classes that are mostly used internally, e.g. `ExcelFieldInfo` to `ExcelColumnInfo`.

The second one won't be so bad, but that first one could be a bit of a headache. Given that, I should really release this as `2.0.0-pre` and accept that it might be a while till these features are in a release version. There are people who legitimately want these features, but it seems worse to break things for existing users.

I'll try to update the assembly version tonight then merge this. @ChrisMissal, I just looked up how to do a pre-release version of a package in NuGet and it's stupidly obvious (put `-pre` at the end of the patch number in the assembly info), so please disregard my silly question from last night if you saw it. Lemme know if you're happy doing a NuGet release some time this week. :)

**Comment by balajichekka** [comment]
Hi Jordan,

how is it going with pre, any planned date for release?

**Comment by jordangray** [comment]
Hey! I haven't had a chance to do much with it in a while, and there's [a few issues I'd like to fix before the 2.0 release](https://github.com/WebApiContrib/WebApiContrib.Formatting.Xlsx/milestones/v2.0%E2%80%94flexibility).

Realistically, given my limited free time for the past few months, I'm unlikely to get through them all for a few months; however, you can find [the prerelease version on NuGet already](https://www.nuget.org/packages/WebApiContrib.Formatting.Xlsx/2.0.0-pre), and I'd love to get some more feedback on it! I know it's a bit sketch using a prerelease version, but it's probably the best option if you need some of the newer stuff now.

(Feel totally free to help if you'd like! I can give you pointers if there's something you'd like to work on. No pressure _whatsoever_, just want to let you know the invitation's open. :) )

**Pull request merged**
